### ISSUE TITLE
defVar error

### ISSUE THREAD

**Issue by bnulzq** [cfranken/SatelliteGridding#7]
The line 342 in `gridL2_Dates.jl`:
`dN = defVar(dsOut,"n",Float32,("time","lon","lat"),deflatelevel=4, fillvalue=-999, units=" ", long_name="Number of pixels in average") #, `

The error appears as:
ERROR: LoadError: MethodError: no method matching defVar(::NCDataset{Nothing, Missing}, ::String, ::Type{Float32}, ::Tuple{String, String, String}; deflatelevel=4, fillvalue=-999, units=" ", long_name="Number of pixels in average")
Closest candidates are:
  defVar(::NCDataset, ::Union{AbstractString, Symbol}, ::DataType, ::Any; chunksizes, shuffle, deflatelevel, checksum, fillvalue, nofill, typename, attrib) at /home/zl725/.julia/packages/NCDatasets/ivzVX/src/cfvariable.jl:99 got unsupported keyword arguments "units", "long_name"
  defVar(::CommonDataModel.AbstractDataset, ::Union{AbstractString, Symbol}, ::DataType, ::Any) at /home/zl725/.julia/packages/CommonDataModel/GGvMn/src/variable.jl:33 got unsupported keyword arguments "deflatelevel", "fillvalue", "units", "long_name"
  defVar(::CommonDataModel.AbstractDataset, ::Union{AbstractString, Symbol}, ::Any, ::Any; kwargs...) at /home/zl725/.julia/packages/CommonDataModel/GGvMn/src/variable.jl:108

And it works out when I just remove the `units=" ", long_name="Number of pixels in average"` in the function

Zhenqi

**Comment by QianqianHan96** [comment]
I had the same error.

**Comment by cfranken** [comment]
My apologies, I haven't change the script in a while. For now, your solution might be a quick fix. When I find time to update, I will take it into consideration. Thanks for the feedback!
